export const ADD_TODO_ITEM = 'ADD_TODO_ITEM'
export const TOGGLE_TODO_ITEM = 'TOGGLE_TODO_ITEM'
export const SET_FILTER = 'SET_FILTER'
export const SET_TODO_ITEM_TEXT = 'SET_TODO_ITEM_TEXT'

export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST'
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE'